### ISSUE TITLE
<AWSframework> framework not found.

### ISSUE THREAD

**Issue by xavicolomer** [awslabs/aws-sdk-react-native#40]
I'm trying to use the aws-sdk-react-native.

1. I downloaded the SDK into ~/Documents/AWSSDK to maintain the same criteria as in FacebookSDK. 
2. I copied the frameworks I wanted to use, I started with all of them, but due to the error I started removing one by one with no luck.

This is the error I am getting (In this case its for AWSCore but it will be any eventually):
```
ld: framework not found AWSCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'd say the instructions could be better. Does anyone succeeded setting this up? Any example?

Thanks!

**Comment by ghost** [comment]
Have you followed these instructions?
https://github.com/awslabs/aws-sdk-react-native/tree/master/Core/example

Some helpful threads related to installing the sdk:
https://github.com/awslabs/aws-sdk-react-native/issues/35
https://github.com/awslabs/aws-sdk-react-native/issues/4
https://github.com/awslabs/aws-sdk-react-native/issues/24

How have you packed the packages and installing them?

**Comment by xavicolomer** [comment]
@bhses Yes. Now I've advanced a little but, but still having some problems. I will be following the main thread now. 

Thanks!
