### ISSUE TITLE
Not able to install lib or just try example

### ISSUE THREAD

**Issue by bintoll** [awslabs/aws-sdk-react-native#53]
Not able to install lib or just try example because in package.json there is a file .tgz that do not exist at all in this repo
![image](https://cloud.githubusercontent.com/assets/20185572/24827011/71fac8ca-1c4b-11e7-9dce-a966ec6f1cb1.png)

**Comment by ghost** [comment]
you have to run `npm pack` in the Core folder in order to create the package

Note, the example is a bit out of date, so check what the name of the pack is.

edit: https://github.com/awslabs/aws-sdk-react-native/blob/master/Core/example/README.md

**Comment by bintoll** [comment]
Thanks! Also i found this .tgz file in Release section. Could you tell me is it possible to use custom identities (not facebook) using this lib?

**Comment by ghost** [comment]
The release section is outdated as well, the current master branch solves some critical problems (also see other issues). Regarding identity providers maybe https://github.com/awslabs/aws-sdk-react-native/blob/master/Core/src/AWSCognitoCredentials.js can give you a hint

**Comment by bintoll** [comment]
Thanks you! Close it)
