### ISSUE TITLE
Still being maintained ? When will the merge happen ?

### ISSUE THREAD

**Issue by petersuwara** [awslabs/aws-sdk-react-native#65]
Hi guys,

We are working closely with the main JavaScript SDK and the syntax for things like SNS here and the main repository are quite different.

Can anyone advise what the future plans are for this ? We don't want to invest in the react-native library if the main repo will do.

It's concerning there hasn't been updates about this review since May, it's now September. I urge you to please give some additional insight on your plans with the repo.

Many thanks.

**Comment by ohtangza** [comment]
Any progress on this? React Native has been grown hugely ever since it has created!

**Comment by alexkuc** [comment]
Would it be too difficult/problematic to use [Javascript SDK](https://github.com/aws/amazon-cognito-identity-js)? I am just about to start learning AWS Cognito hence asking.

**Comment by ohtangza** [comment]
@alexkuc React Native with JS SDK doesn't support Cognito authentication well for now. You need to use the 3rd-party module like https://github.com/AirLabsTeam/react-native-aws-cognito-js.

**Comment by alexkuc** [comment]
@ohtangza How come? Is it due to dependencies resolution (e.g. webpack)?

**Comment by ohtangza** [comment]
@alexkuc 

- The authentication is known to be way too slow. (The reason the author made the repo I mentioned above) I think it's because RN uses the built-in JS engine on each mobile platform. 

- There is also known issue that the logged in status does not persist across session, so user might be logged out after re-launching the app.

**Comment by alexkuc** [comment]
@ohtangza Ah! Thank you very much for explaining!

**Comment by appwiz** [comment]
Hi everyone, thank you for your interest in this project. We've released a new React Native starter kit at https://github.com/awslabs/aws-mobile-react-native-starter. This kit demonstrates a working React Native app with the following services:
- Amazon Cognito User Pools
- Amazon Cognito Federated Identities
- Amazon API Gateway
- AWS Lambda
- Amazon DynamoDB
- Amazon S3
- AWS Mobile Hub

Try it out and give us feedback.

**Comment by ChristophRob** [comment]
I LIKE! Please put that link right on the top of this projects README.md

**Comment by chapeljuice** [comment]
So does that mean this repo is no longer being updated / maintained? Enquiring minds want to know! :)

**Comment by undefobj** [comment]
Hi - We've been listening to much customer feedback in these areas, including the slow login issue for React Native when using Cognito User Pools, and have developed a new, comprehensive JavaScript library with specific components and extensions for React and React Native (which also addresses the slow login issue). Please take a look at it here: https://github.com/aws/aws-amplify
